version: '3.7'

services:
    middleware:
        build: 
          context: ./middleware
          dockerfile: Dockerfile       
        ports:
          - 5000:5000
    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        ports:
          - '3000:3000'
        environment:
          - NODE_ENV=development
        links:
          - middleware